platina: Squash import of camera HAL
camera: isEmpty() -> empty()

Change-Id: I4d518bebe740846f0d8c38d3e74a9c46fd40b873

camera: Allow unused variables

camera: Fix snprintf string truncation error

* Now we truncate the string by ourselves, instead of letting snprintf
  to do so, which causes compilation error on U QPR3...

camera: String8::string() => String8::c_str()

camera: Fix duplicated symbol mm_camera_shim_module_init

camera: Guard hal1 specific variables

Change-Id: Ic27204edf5879814ba5a091a41afb950f838ab83

camera: update metadata

camera: Match metadata_data_t

camera : remove IS_TYPE_VENDOR_EIS

Revert "QCamera2: Added enum to enable Third Party EIS"

This reverts commit a64d1d8ff6f5772863f274b13ae44ec0428d7684.

Revert "Increase request count array for future frame usecases to avoid"

This reverts commit 0c8a843ca76921995456b83ca44f941ffe73c4b5.

Revert "Extend get RAW param to query sensor oppixel clock."

This reverts commit 402dbfa0a7544cc6f3fafc5981f36cd381f7ad44.

camera: Revert "QCamera2: HAL3: tranfer in sensor qcfa mode to HAL"

This reverts commit 2f7ac366b4b860eed76fa6fa10070a93370534b6.

camera: Revert "QCamera2: Adding support for msm-4.19"

This reverts commit 60d68ecbb9a8fd0fa529a10010478a04dd7c5c99.

camera: Revert "QCamera2: Use safe string functions"

This reverts commit efbe9736e92998dc35bf828471f877bedf6ab12d

camera: Revert "Add support for thermal shutdown in HAL3."

This reverts commit 9ad1639b1ce11e0556fdce88238cea21f111bd5d.

camera: Fix misleading indentions

* error: misleading indentation; statement is not part of the previous 'if' [-Werror,-Wmisleading-indentation]

camera: Skip loading libthermalclient

- It delays when switching between cameras or modes in our case

camera: Use log/log.h instead of utils/Log.h

camera: Export the interface headers

Export the interface headers needed by the vendor

Signed-off-by: Alin Jerpelea <alin.jerpelea@sony.com>

camera: QCamera3Stream: Fix concatenation of string literals in the array

vendor/qcom/opensource/camera/QCamera2/HAL3/QCamera3Stream.cpp:59:9:
error: suspicious concatenation of string literals in an array
initialization; did you me
an to separate the elements with a comma?
[-Werror,-Wstring-concatenation]
        "CAM_MAX" };
        ^

camera: Switch to display_headers lib include

LOCAL_COPY_HEADERS is deprecated and Qualcomm HALs have been
updated to remove its usage. As a consequence, the display headers
are no longer copied to TARGET_OUT_HEADERS, so use the equivalent
header lib instead.

Change-Id: I85d229e536146b86662e9c9a28017d2448c856dd

camera: Fix build with BOARD_VNDK_VERSION

Add missing header dependency and include system headers explicitly.

Signed-off-by: Alin Jerpelea <alin.jerpelea@sony.com>

camera: Fix build with BOARD_VNDK_VERSION

Add libutils to camera modules.

Signed-off-by: Alin Jerpelea <alin.jerpelea@sony.com>

camera: Fix the undeclared variable

the info variable is used only when QCAMERA_HAL1_SUPPORT is enabled

Signed-off-by: Alin Jerpelea <alin.jerpelea@sony.com>

camera: Resolve incorrect increment in for loop

Issue:  When QCameraHeapMemory::allocate() is done mapping buffers the
remaining allocated buffers need to be dellocated ,but because
of
        incorrect incrememt this is failing

Fix: To resolve issue we need to correct the increment for the for loop
     where the process is happening

camera: QCamera2: The picture show overexpose

set AUTO_EXPOSURE_CENTER_WEIGHTED

Change-Id: I133eb316ec316ec6e41db71f206fb25eccafa443
Signed-off-by: David Trpchevski <trpcevski.david@gmail.com>

camera: QCamera2: Enable antibanding to fix the flickers issue

The GMS Camera app does not have antibanding setting.
So set default antibanding setting as Auto.

Change-Id: Ia61e9623a6c180a1c2a972b6c16eb7b2277a2393
Signed-off-by: David Trpchevski <trpcevski.david@gmail.com>

camera: mm-camera-channel: Added check for max value of cur_capture_idx

Issue: In FLASH mode, while requesting superBuffers for 100 snapshots
      cur_capture_idx is increasing to more that MAX_CAPTURE_BATCH_NUM,
      so by derefrencing frameConfig.config to cur_capture_idx, stack
      memory is getting corrupted.

Solution: Checking for max value of cur_capture_idx before derefrencing
          frameConfig.config array to avoid writing in outOfBound index
          memory.

Change-Id: Icaea62be483b3ee97304441f7c9287b73496f09d

camera: Increase MM_CAMERA_DEV_OPEN_RETRY_SLEEP retries

camera: Switch to CAM_ISO_MODE_AUTO for ISO_HFR

* It looks like CAM_ISO_MODE_DEBLUR is broken in the backend

camera: Display correct refresh rate for maxFPS

Issue: Framework expecting refresh rate to be displayed as float value
       but we have variable maxFPS as integer, so the value is being
       displayed as 0 and not a decimal value (float).

Fix : Create a variable called refreshShow as a float and make it equal
      to float of mMaxFPS so that framework can get proper refresh rate
      to be displayed for maxFPS.

camera: Improve min frame rate hack

AFAIK, there are apps that request 15fps min frame rate; this is
deliberate and we shouldn't change its default behaviour. But anything
that sets the min fps the same as the max fps definitely should just
stop.

Change-Id: I5c3a31241009ab79edba4191910ad99d2db30f71

camera: Hardcode preview fps range

* If userspace does not specify a range, it would be defaulted to
   30000,30000 (30-30fps), which causes really bad exposure under
   low light during video recording in certain apps (SnapdragonCamera
   for one *cough cough*). We definitly do not want this.
 * Work around this issue by always forcing min fps of 7.

camera: Make mm-image-codec build with the VNDK

When the vndk is enabled (BOARD_VNDK_VERSION=current),
vendor libraries must only link against vendor variants
in the build system. This also means that they receive
restricted sets of headers and that automatic global
headers are restricted.

Test: build mm-image-codec with BOARD_VNDK_VERSION=current
Bug: 69526027
Change-Id: I4ef73cd39c1731c85fb2653eb4d5c74037407f88

camera: QCamera2/HAL3: Correct mutex lock/unlock sequence

Bug: 36716469
CRs-Fixed: 2053027
Change-Id: I6699c3682eec419fb6efb0583e9909e5739476a0

camera: QCamera2: HAL3: Handle out of order buffers correctly

Sometimes, the stream buffers come in disorder,
treat the disordered frames as error frames.

Test: Camera CTS
Bug: 37657585
Change-Id: I910153e9216ed7a83648663176c58d3696b27107
Signed-off-by: clarencelol <clarencekuiek@icloud.com>

camera: Optimize startup by not loading a library to check a constant

The camera HAL needs to know the stride padding value for buffers.
This is found by dlopening a graphics utility library, calling one
method in it, and then closing the library.

Since this value is a constant, just hard code the value returned
for marlin/sailfish.

Test: Camera CTS passes
Bug: 38202666
Change-Id: Ie2fd03874aea41b81ad0a6f59eab244bf573b838

camera: HAL3: Reduce buffer counts

When EIS3 is enabled, further optimize below buffer counts:
* For 4K video buffer count 30-->18
* For other video buffer count: 30-->24

Also reduce the BLOB count from 10 to 3.

These reduced the peak pressure by up to 200--300MB.

Bug: 62331291
Change-Id: I95cf8fede3a73f50ba737d34bcc0e52260f0b794

camera: Expose inline function mm_jpeg_get_comp_name to linker

* It is needed for gcov build as no compiler optimization is done with
  gcov build.

Test: lunch walleye_coverage-userdebug && make
Change-Id: I1b154b5e597e89d41708174fbc8697bd2cccfaa4

camera: QCamera2: HAL3: Advertise dynamic black level

When optical black region isn't available, still advertise dynamic black
level since it could be generated by ISP.

Test: Camera CTS
Bug: 65693861
Change-Id: Id43411a4a3cea269a5e1970de4e373175b5e40ec

camera: QCamera2: HAL3: Fix VTS failures

- Per API contract in case flash is not supported Hal should return
"-ENOSYS" as error code.
- Hal should fail when the configured stream rotation value is invalid.

Bug: 63130431
Test: adb shell
/data/nativetest/VtsHalCameraProviderV2_4TargetTest/VtsHalCameraProviderV2_4TargetTest
Change-Id: Ief7049d4b726943d65a865d7e295fe6b1697b118

camera: Increase frame timeouts to allow for longer exposures

Increase frame timeout to 10 seconds from 5, to allow at least
4-second exposures with some margin.

Test: Camera CTS continues to pass, manual exposures look OK
Bug: 38212789
Change-Id: I7279a5b0d431c966288c6e965f125b27f0b635cb

camera: QCamera2: HAL3: Fix wrong conversion for first 2 pixels

Test: Camera CTS
Bug: 65552901
Change-Id: I3ee00beb9ebef811e74e95134ead886e3da6d476

camera: Fix LSB 2 bits fetching bug

Test: compare with RAW10 output
Bug: 65552901
Change-Id: I5104571fd18ec6df2ecebb0433db4aaaec6e4be8

camera: QCamera: Buffer enqueue fails in secure camera use case

Issue: Dequeued buffers from display are not getting owned due to
       improper logic in secure callback routine and subsequently
       while enqueuing same buffer to display, enqueue buffer is
       getting failed.

Fix: Buffer done must be done on dequeued buffer index from display.

Change-Id: Ib778456860625356068a669ad8c2c365ed645a5b

camera: QCamera2: QCameraParamters: ASAN fix for heap-use-after-free in setLongShotParam

Issue: ASAN failed with error "heap-use-after-free" in setLongShotParam.

Solution: Doing strcmp before setting KEY_QC_LONG_SHOT as "set" will
release
           prev_str memory from the vector list.

Change-Id: I1f67791a895308ace6f4c9785616cef474d3d674

camera: QCamera2: HAL3: Fix missing pthread unlock

Test: Camera CTS
Bug: 36716469
Change-Id: I6699c3682eec419fb6efb0583e9909e5739476a0

camera: hw-qcom-camera: Completed FR49059 and FR49058

FR49059: Accessing AOSP/Google projects Headers

Description: Vendor modules cannot refer AOSP header
paths with absolute or Global Paths instead add
corresponding header library

FR49058 :  VNDK compliance

Description : VNDK is set of AOSP libraries which
are exposed to vendor (partition) for development.

Example :

error: vendor lib "/vendor/lib/libeffects.so"
 depends on non-eligible lib
 "/system/lib/libeffectsconfig.so".
Here , QCOM vendor-partition Library
using lib outside VNDK from system.

CRs-Fixed: 2217547

Change-Id: I51a88145fccba592080d6287ae7ff14d12c65296

camera: Do not use perfd by default

Add persist.camera.perfd.enable to disable/enable perfd connection from
CameraHAL.

Bug: 63589458
Test: Test powerHAL hint working with camera and there is no perfd
interaction
Change-Id: Ic288a494be995f24cc85ceb69539aeb0a2d174c3

camera: Fix dependencies for mm-camera-interface

Test: mma -j BOARD_VNDK_VERSION=current
Bug: 33241851
Change-Id: I603e86e78c80e592e852da184ca021fe42a8ea9a

camera: Remove CAF conditional

call is-vendor-board-platform,QCOM is unknown by AOSP system ... remove
this one in favour of kernel headers flag

also add missing DEPENDENCIES for kernel headers

Signed-off-by: David Viteri <davidteri91@gmail.com>

camera: QCamera2: Remove absolute path for shimlayer lib

there is no need for an absolute path here since the lib can be found
dynamically

camera: Improve ZSL/HDR processing

* Allocate enough buffer for HDR snapshot.

Change-Id: I84b1186e5342f8243dbca9a5bf854241b8b197c1

camera: Don't advertise CDS mode values in HAL1

* Some camera apps are using cds-mode-values to determine CDS support.
* We don't want this as CDS is broken with the new kernel driver.

Change-Id: I7aa317d2a729c222f8881e76ba060a64c12413b1

camera: Don't advertise YUV/PRIVATE reprocessing capabilities

These capabilities are used for ZSL support in HAL3.
Our camera stack has issues with YUV reprocessing, so we should not
expose them for now.

Change-Id: Idd89300f415c83446ffd7c4c9823a947a9cd6f86

camera: Fix setCameraLaunchStatus

* Fixes slow camera launch

camera: Fix cleanstep file name

Signed-off-by: Davide Garberi <dade.garberi@gmail.com>
Change-Id: I5e73d93e36cb4fb0187f29b0b9d730a829733aca

camera: Filter out lib2d-interface

Signed-off-by: OdSazib <odsazib@gmail.com>
Change-Id: I8599bb8b5745845f47b7432b4175b14318d76704

camera: Guard lib2d rotation with QCPATH

camera: Drop usage of LOCAL_COPY_HEADERS

Google deprecated LOCAL_COPY_HEADERS in Android 11,
so use LOCAL_EXPORT_C_INCLUDE_DIRS instead.

Ref:
https://android.googlesource.com/platform/build/soong/+/master/docs/best_practices.md#headers.

Change-Id: Id68bc83cf74f2af0037331ebe4d17819021b88e8

camera: mm-lib2d-interface: Use generated kernel headers

camera: Link to libhidltransport instead of android.hidl.base

camera: Fix HAL paths

Signed-off-by: Pranav Kapoor <pranavkapoor001@gmail.com>

camera: Fix path for in-tree build

Signed-off-by: SayanAcharya <rowdysayan99@gmail.com>
Change-Id: Ic180a59dfa52d81484471e0b6e630fe545cdaef4

camera: Remove unused files

Change-Id: I0c717d165162469ba4b78ea07da6dd88b5cfc18a

camera: Disable lib2d rotation

* Requires proprietary header

Change-Id: I79ab131e935dc8e3239b7cfd9c27933f90669c24

camera: Import from LA.UM.11.2.1.r1-03100-sdm660.0

Change-Id: I1b785564107059434e412fe9c64925380dbba00e

Change-Id: I426d21e32a05d4b4f440c7951af558e956d5a720
Co-Authored-By: 0xCAFEBABE <87921983+me-cafebabe@users.noreply.github.com>
Co-Authored-By: Edwin Moquete <edwinmmoquete@gmail.com>
Signed-off-by: HeroBuxx <me@herobuxx.me>
Signed-off-by: Raya Mahardika <94042378+rktdnt@users.noreply.github.com>